In [8]:
import numpy as np
import pandas as pd

In [13]:
import numpy as np
import pandas as pd
labels = [1, 2, 3]
data = {
    'Name': ['Zihad', 'Rifat', 'Sakib'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000],
    'Home Town': ['Dhaka', 'Chittagong', 'Khulna']
}

In [20]:
df = pd.DataFrame(data)
df

    Name  Age  Salary   Home Town
0  Zihad   25   50000       Dhaka
1  Rifat   30   60000  Chittagong
2  Sakib   35   70000      Khulna

In [16]:
df = pd.DataFrame(data, index=labels)
df

    Name  Age  Salary   Home Town
1  Zihad   25   50000       Dhaka
2  Rifat   30   60000  Chittagong
3  Sakib   35   70000      Khulna

In [17]:
df

    Name  Age  Salary   Home Town
1  Zihad   25   50000       Dhaka
2  Rifat   30   60000  Chittagong
3  Sakib   35   70000      Khulna

In [26]:
data_list = [
    ['zihad','akib','sakib'],
    [25, 30, 35],
    [50000, 60000, 70000],
    ['Dhaka', 'Chittagong', 'Khulna']
]
labels = ['Name', 'Age', 'Salary', 'Home Town']
df = pd.DataFrame(data=data_list, index=labels)
df

               0           1       2
Name       zihad        akib   sakib
Age           25          30      35
Salary     50000       60000   70000
Home Town  Dhaka  Chittagong  Khulna

In [29]:
data_list = [
    ['Zihad', 25, 50000, 'Dhaka'],
    ['Rifat', 30, 60000, 'Chittagong'],
    ['Sakib', 35, 70000, 'Khulna']
]
indices = [1, 2, 3]
labels = ['Name', 'Age', 'Salary', 'Home Town']
df = pd.DataFrame(data=data_list, index=indices, columns=labels)
df

    Name  Age  Salary   Home Town
1  Zihad   25   50000       Dhaka
2  Rifat   30   60000  Chittagong
3  Sakib   35   70000      Khulna

In [30]:
df[['Name', 'Salary']]

    Name  Salary
1  Zihad   50000
2  Rifat   60000
3  Sakib   70000

In [31]:
df[['Name']]

    Name
1  Zihad
2  Rifat
3  Sakib

In [32]:
df["designation"] = ['Data Scientist', 'Data Analyst', 'Data Engineer']

In [33]:
df

    Name  Age  Salary   Home Town     designation
1  Zihad   25   50000       Dhaka  Data Scientist
2  Rifat   30   60000  Chittagong    Data Analyst
3  Sakib   35   70000      Khulna   Data Engineer

In [35]:
df.drop('Name',axis=1)

   Age  Salary   Home Town     designation
1   25   50000       Dhaka  Data Scientist
2   30   60000  Chittagong    Data Analyst
3   35   70000      Khulna   Data Engineer

In [36]:
df.loc[1]

Name                    Zihad
Age                        25
Salary                  50000
Home Town               Dhaka
designation    Data Scientist
Name: 1, dtype: object

In [43]:
df.loc[[3,1]]

    Name  Age  Salary Home Town     designation
3  Sakib   35   70000    Khulna   Data Engineer
1  Zihad   25   50000     Dhaka  Data Scientist

In [ ]:
df.iloc[2] 
#only index based selection

Name                   Sakib
Age                       35
Salary                 70000
Home Town             Khulna
designation    Data Engineer
Name: 3, dtype: object

In [51]:
df.loc[[1,3],['Name','Salary']]

    Name  Salary
1  Zihad   50000
3  Sakib   70000

In [56]:
df [ df['Salary'] > 50000 ]

df[df['Salary'] > 50000][['Name','Salary'] ]

    Name  Salary
2  Rifat   60000
3  Sakib   70000

In [54]:
df[df['Salary'] > 50000]

    Name  Age  Salary   Home Town    designation
2  Rifat   30   60000  Chittagong   Data Analyst
3  Sakib   35   70000      Khulna  Data Engineer

In [58]:
df[(df['Salary'] > 50000) & (df['Age'] > 30)]

    Name  Age  Salary Home Town    designation
3  Sakib   35   70000    Khulna  Data Engineer