In [1]:
import numpy as np
import pandas as pd

In [6]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "department": ["HR", "IT", "Finance", "IT", "Marketing"]
})
salaries = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5],
    "salary": [50000, 60000, 55000, 70000, 65000],
    "bonus":[2000, 3000, 2500, 4000, 3500]
})

In [7]:
employees

   employee_id     name department
0            1    Alice         HR
1            2      Bob         IT
2            3  Charlie    Finance
3            4    David         IT
4            5      Eve  Marketing

In [8]:
print(employees)
print(salaries)

   employee_id     name department
0            1    Alice         HR
1            2      Bob         IT
2            3  Charlie    Finance
3            4    David         IT
4            5      Eve  Marketing
   employee_id  salary  bonus
0            1   50000   2000
1            2   60000   3000
2            3   55000   2500
3            4   70000   4000
4            5   65000   3500

In [11]:
employees_with_salaries = pd.merge(employees, salaries, on = "employee_id", how = "inner")
print(employees_with_salaries)

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [12]:
pd.merge(employees, salaries, on = "employee_id", how = "outer")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [13]:
pd.merge(employees, salaries, on = "employee_id", how = "left")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [14]:
pd.merge(employees, salaries, on = "employee_id", how = "right")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500