In [1]:
import numpy as np
import pandas as pd

In [6]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "department": ["HR", "IT", "Finance", "IT", "Marketing"]
})
salaries = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5],
    "salary": [50000, 60000, 55000, 70000, 65000],
    "bonus":[2000, 3000, 2500, 4000, 3500]
})

In [7]:
employees

   employee_id     name department
0            1    Alice         HR
1            2      Bob         IT
2            3  Charlie    Finance
3            4    David         IT
4            5      Eve  Marketing

In [8]:
print(employees)
print(salaries)

   employee_id     name department
0            1    Alice         HR
1            2      Bob         IT
2            3  Charlie    Finance
3            4    David         IT
4            5      Eve  Marketing
   employee_id  salary  bonus
0            1   50000   2000
1            2   60000   3000
2            3   55000   2500
3            4   70000   4000
4            5   65000   3500

In [11]:
employees_with_salaries = pd.merge(employees, salaries, on = "employee_id", how = "inner")
print(employees_with_salaries)

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [12]:
pd.merge(employees, salaries, on = "employee_id", how = "outer")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [13]:
pd.merge(employees, salaries, on = "employee_id", how = "left")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [14]:
pd.merge(employees, salaries, on = "employee_id", how = "right")

   employee_id     name department  salary  bonus
0            1    Alice         HR   50000   2000
1            2      Bob         IT   60000   3000
2            3  Charlie    Finance   55000   2500
3            4    David         IT   70000   4000
4            5      Eve  Marketing   65000   3500

In [15]:
pd.concat([employees, salaries], axis = 0)

   employee_id     name department   salary   bonus
0            1    Alice         HR      NaN     NaN
1            2      Bob         IT      NaN     NaN
2            3  Charlie    Finance      NaN     NaN
3            4    David         IT      NaN     NaN
4            5      Eve  Marketing      NaN     NaN
0            1      NaN        NaN  50000.0  2000.0
1            2      NaN        NaN  60000.0  3000.0
2            3      NaN        NaN  55000.0  2500.0
3            4      NaN        NaN  70000.0  4000.0
4            5      NaN        NaN  65000.0  3500.0

In [16]:
pd.concat([employees, salaries], axis = 1)

   employee_id     name department  employee_id  salary  bonus
0            1    Alice         HR            1   50000   2000
1            2      Bob         IT            2   60000   3000
2            3  Charlie    Finance            3   55000   2500
3            4    David         IT            4   70000   4000
4            5      Eve  Marketing            5   65000   3500

In [22]:
df1 = pd.DataFrame({
    "A": ["A0", "A1", "A2", "A3"],
    "B": ["B0", "B1", "B2", "B3"],
    "C": ["C0", "C1", "C2", "C3"],
    "D": ["D0", "D1", "D2", "D3"]
})
df2 = pd.DataFrame({
    "E": ["E4", "E5", "E6", "E7"],
    "F": ["F4", "F5", "F6", "F7"],
    "G": ["G4", "G5", "G6", "G7"],
    "H": ["H4", "H5", "H6", "H7"]
})

In [23]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [24]:
print(df1)
print(df2)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    E   F   G   H
0  E4  F4  G4  H4
1  E5  F5  G5  H5
2  E6  F6  G6  H6
3  E7  F7  G7  H7

In [20]:
pd.concat([df1, df2], axis = 0)

     A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   E4   F4   G4   H4
5  NaN  NaN  NaN  NaN   E5   F5   G5   H5
6  NaN  NaN  NaN  NaN   E6   F6   G6   H6
7  NaN  NaN  NaN  NaN   E7   F7   G7   H7

In [21]:
pd.concat([df1, df2], axis = 1)

     A    B    C    D    E    F    G    H
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   E4   F4   G4   H4
5  NaN  NaN  NaN  NaN   E5   F5   G5   H5
6  NaN  NaN  NaN  NaN   E6   F6   G6   H6
7  NaN  NaN  NaN  NaN   E7   F7   G7   H7

In [36]:
df3 = pd.DataFrame({
    "name":['alice','henry','tom']
},index = [1,2,3]
)
df4 = pd.DataFrame({
    "score": [78,88,97]
},index = [2,3,4]
)

In [37]:
df3

    name
1  alice
2  henry
3    tom

In [38]:
df4

   score
2     78
3     88
4     97

In [39]:
df3.join(df4,how = "outer")

    name  score
1  alice    NaN
2  henry   78.0
3    tom   88.0
4    NaN   97.0

In [40]:
df4.join(df3)

   score   name
2     78  henry
3     88    tom
4     97    NaN

In [41]:
df3.join(df4)

    name  score
1  alice    NaN
2  henry   78.0
3    tom   88.0