In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'A': [1, 2, np.nan, 4],
    'B': [np.nan, 2, 3, 4],
    'C': [1, np.nan, 3, 4],
    'D': [np.nan, np.nan, np.nan, np.nan],
    'E': [1, 2, 3, 4]
}

In [6]:
df

     A    B    C   D  E
0  1.0  NaN  1.0 NaN  1
1  2.0  2.0  NaN NaN  2
2  NaN  3.0  3.0 NaN  3
3  4.0  4.0  4.0 NaN  4

In [8]:
df = pd.DataFrame(data)
print(df)

     A    B    C   D  E
0  1.0  NaN  1.0 NaN  1
1  2.0  2.0  NaN NaN  2
2  NaN  3.0  3.0 NaN  3
3  4.0  4.0  4.0 NaN  4

In [13]:
column = [1,2,3,4]
df = pd.DataFrame(data, index=column)
print(df)

     A    B    C   D  E
1  1.0  NaN  1.0 NaN  1
2  2.0  2.0  NaN NaN  2
3  NaN  3.0  3.0 NaN  3
4  4.0  4.0  4.0 NaN  4

In [15]:
df.isna().sum() #how many nan in a column shows

A    1
B    1
C    1
D    4
E    0
dtype: int64

In [16]:
df.isna().any() #if any nan in a column shows True or False

A     True
B     True
C     True
D     True
E    False
dtype: bool

In [17]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [18]:
df.dropna(thresh=1)

     A    B    C   D  E
1  1.0  NaN  1.0 NaN  1
2  2.0  2.0  NaN NaN  2
3  NaN  3.0  3.0 NaN  3
4  4.0  4.0  4.0 NaN  4

In [20]:
print(df)

     A    B    C   D  E
1  1.0  NaN  1.0 NaN  1
2  2.0  2.0  NaN NaN  2
3  NaN  3.0  3.0 NaN  3
4  4.0  4.0  4.0 NaN  4

In [21]:
df.fillna(0) #fill nan with 0

     A    B    C    D  E
1  1.0  0.0  1.0  0.0  1
2  2.0  2.0  0.0  0.0  2
3  0.0  3.0  3.0  0.0  3
4  4.0  4.0  4.0  0.0  4

In [24]:
df.fillna(df.mean()) #fill nan with mean of the column
print(df.fillna(df.mean()))

          A    B         C   D  E
1  1.000000  3.0  1.000000 NaN  1
2  2.000000  2.0  2.666667 NaN  2
3  2.333333  3.0  3.000000 NaN  3
4  4.000000  4.0  4.000000 NaN  4

In [26]:
values = {
    'A': 5,
    'B': 12,
    'C': 26,
    'D': 33,
    'E': 43
}
print(df.fillna(value=values)) #fill nan with a list of values

     A     B     C     D  E
1  1.0  12.0   1.0  33.0  1
2  2.0   2.0  26.0  33.0  2
3  5.0   3.0   3.0  33.0  3
4  4.0   4.0   4.0  33.0  4

In [29]:
print(df)

     A    B    C   D  E
1  1.0  NaN  1.0 NaN  1
2  2.0  2.0  NaN NaN  2
3  NaN  3.0  3.0 NaN  3
4  4.0  4.0  4.0 NaN  4