In [4]:
import numpy as np
import pandas as pd

In [9]:
df = pd.DataFrame({
    "A":range(1,6),
    "B":range(10,60,10),
    "C":range(100,600,100)
})
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [10]:
print(df)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [12]:
df.shape

(5, 3)

In [16]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [14]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [15]:
df.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [17]:
df.describe

<bound method NDFrame.describe of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [18]:
df['A']*5

0     5
1    10
2    15
3    20
4    25
Name: A, dtype: int64

In [28]:
df["D"] = df["B"].apply(lambda x : x**2)
df.drop(columns=['d'])
print(df)

   A   B    C     d     D
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500

In [29]:
df.drop(columns=["d"])

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [31]:
print(df)
df.drop(columns=['d'])

   A   B    C     d     D
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500